// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWNN62B6e1kr8BiLWV6LOKTm56RNPvfdA',
    appId: '1:560405524621:web:79d9d6d09551e1cdd4f2c4',
    messagingSenderId: '560405524621',
    projectId: 'miniproject-bf621',
    authDomain: 'miniproject-bf621.firebaseapp.com',
    storageBucket: 'miniproject-bf621.firebasestorage.app',
    measurementId: 'G-X2473PNM24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPKLMmQ5AEv9w1V9kviEzTZRBOYa9s8OU',
    appId: '1:560405524621:android:37497a0e3a4e6e75d4f2c4',
    messagingSenderId: '560405524621',
    projectId: 'miniproject-bf621',
    storageBucket: 'miniproject-bf621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmNB990do9ht26OUrG5gyq7zDe79ip5k',
    appId: '1:560405524621:ios:aada102664281860d4f2c4',
    messagingSenderId: '560405524621',
    projectId: 'miniproject-bf621',
    storageBucket: 'miniproject-bf621.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVmNB990do9ht26OUrG5gyq7zDe79ip5k',
    appId: '1:560405524621:ios:aada102664281860d4f2c4',
    messagingSenderId: '560405524621',
    projectId: 'miniproject-bf621',
    storageBucket: 'miniproject-bf621.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWNN62B6e1kr8BiLWV6LOKTm56RNPvfdA',
    appId: '1:560405524621:web:c9fd4882966e0aefd4f2c4',
    messagingSenderId: '560405524621',
    projectId: 'miniproject-bf621',
    authDomain: 'miniproject-bf621.firebaseapp.com',
    storageBucket: 'miniproject-bf621.firebasestorage.app',
    measurementId: 'G-MB1026MEZX',
  );
}
